project:
  type: website

website:
  title: "Ava Godsy"
  navbar:
    left:
      - text: About Me
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



